# Generated by Django 3.2.11 on 2022-02-14 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CampoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_campo', models.CharField(max_length=252, verbose_name='Nombre del campo')),
                ('tipo', models.PositiveIntegerField(choices=[(1, 'Texto'), (2, 'Fecha'), (3, 'Lista'), (4, 'Caja de área de texto')], verbose_name='Tipo de campo')),
                ('values_select', models.TextField(blank=True, null=True, verbose_name='Valores de la lista')),
                ('is_required', models.BooleanField(verbose_name='¿Campo requerido?')),
            ],
        ),
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual el objeto fue creado.', verbose_name='create at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='modified at')),
                ('nombre', models.CharField(max_length=252, verbose_name='Nombre de la encuesta')),
                ('descripcion', models.TextField(verbose_name='Descripción de la encuesta')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RespuestaCampo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en la cual el objeto fue creado.', verbose_name='create at')),
                ('modified', models.DateTimeField(auto_now=True, help_text='Fecha y hora de la última modificación del objeto.', verbose_name='modified at')),
                ('respuesta', models.CharField(max_length=1024)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='encuestas.encuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas', to='encuestas.campoencuesta')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': 'created',
                'abstract': False,
            },
        ),
    ]
