# Generated by Django 3.2.11 on 2022-02-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_encuesta_estado_terminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestacampo',
            name='encuesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.encuesta'),
        ),
        migrations.AlterField(
            model_name='respuestacampo',
            name='pregunta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='encuestas.campoencuesta'),
        ),
    ]
