# Generated by Django 3.2.11 on 2022-02-21 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0004_auto_20220216_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Encuesta activada'),
        ),
    ]
