# Generated by Django 3.2.11 on 2022-02-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0005_encuesta_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoencuesta',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Pregunta activada'),
        ),
    ]
